# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('exam_1', models.BooleanField(default=True)),
                ('exam_2', models.BooleanField(default=True)),
                ('exam_3', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('url_img', models.CharField(max_length=355)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
